
swagger: '2.0'
info:
  version: '1.0.0'
  title: Factory Management System API
  description: API documentation for the Factory Management System
host: 'localhost:5000'
schemes:
  - http
paths:
  /employees:
    get:
      summary: Get all employees
      description: Returns a list of all employees in the system.
      responses:
        '200':
          description: A list of employees.
          schema:
            type: array
            items:
              $ref: '#/definitions/Employee'
    post:
      summary: Create an employee
      description: Adds a new employee to the system.
      parameters:
        - in: body
          name: body
          description: Employee object that needs to be added to the system
          required: true
          schema:
            $ref: '#/definitions/Employee'
      responses:
        '201':
          description: Employee created successfully.
  /customers:
    get:
      summary: Get all customers
      description: Returns a list of all customers in the system.
      responses:
        '200':
          description: A list of customers.
          schema:
            type: array
            items:
              $ref: '#/definitions/Customer'
definitions:
  Employee:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
      position:
        type: string
  Customer:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
      email:
        type: string
