
swagger: "2.0"
info:
  version: "1.0.0"
  title: "E-Commerce API"
  description: "API documentation for the E-Commerce system"
host: "localhost:5000"
basePath: "/api"
schemes:
  - "http"
paths:
  /products:
    get:
      summary: "Retrieve a list of products"
      responses:
        200:
          description: "A list of products"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Product"
    post:
      summary: "Create a new product"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            $ref: "#/definitions/ProductInput"
      responses:
        201:
          description: "Product created successfully"
  /products/{id}:
    get:
      summary: "Retrieve a product by ID"
      parameters:
        - in: "path"
          name: "id"
          required: true
          type: "string"
      responses:
        200:
          description: "Product retrieved successfully"
          schema:
            $ref: "#/definitions/Product"
definitions:
  Product:
    type: "object"
    properties:
      id:
        type: "string"
      name:
        type: "string"
      price:
        type: "number"
  ProductInput:
    type: "object"
    properties:
      name:
        type: "string"
      price:
        type: "number"
